#server:
#  port: 8080

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password: sa
#      initialize: false
#      generate-unique-name: false
#      jpa:
#        hibernate:
#          ddl-auto: create
#        show-sql: true
#        database-platform: org.hibernate.dialect.H2Dialect

